Version 2.3.4

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -34,7 +34,7 @@ SED="sed"
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
 TEXINPSEP=":" #Unix
 #TEXINPSEP=";"  #MS Windows
-VERSION="1.30"
+VERSION="1.40"
 
 help()
 {
@@ -78,6 +78,7 @@ home_dir="."    # default to current directory
 ext="tex"       # default to latex input
 out="-depth 24" # default to color output
 inline=0        # default to no special equation processing
+tikz=0          # default to not processing a tikzpicture
 
 while [ -n "$1" ]; do
 case $1 in
@@ -131,25 +132,14 @@ if [ $ext = "tex" ] ; then
 
     inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
 
+    tikz=`${GREP} -c tikzpicture $name.$ext`
+
     rm -f $name.dvi
     rm -f $name.pdf
     rm -f $name.eps
     rm -f $name.png
 
-    $LATEX $name > /dev/null
-    
-    if [ -e "$name.dvi" ] ; then
-       $DVIPS -o $name.eps $name.dvi
-       if [ ! -e "$name.eps" ] ; then
-         if [ $opt_k -eq 1 ] ; then
-            echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
-         fi
-         exit 1
-       fi
-    else
-       if [ $opt_k -eq 1 ] ; then
-          echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
-       fi
+    if [ $tikz -gt 1 ] ; then
        $PDFLATEX $name > /dev/null
        if [ -e "$name.pdf" ] ; then
           $PDF2EPS $name.pdf $name.eps
@@ -165,12 +155,50 @@ if [ $ext = "tex" ] ; then
           if [ -e "$name.pdf" ] ; then
              $PDF2EPS $name.pdf $name.eps
              if [ ! -e "$name.eps" ] ; then
+                echo "latex2png: error: $PDF2EPS failed to translate $name.pdf to $name.eps"
+                exit 1
+             fi
+          else
+             echo "latex2png: error: $XELATEX failed to translate $name.tex to $name.pdf"
+             exit 1
+          fi
+       fi
+    else
+       $LATEX $name > /dev/null
+       if [ -e "$name.dvi" ] ; then
+          $DVIPS -o $name.eps $name.dvi
+          if [ ! -e "$name.eps" ] ; then
+            if [ $opt_k -eq 1 ] ; then
+               echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
+            fi
+            exit 1
+          fi
+       else
+          if [ $opt_k -eq 1 ] ; then
+             echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
+          fi
+          $PDFLATEX $name > /dev/null
+          if [ -e "$name.pdf" ] ; then
+             $PDF2EPS $name.pdf $name.eps
+             if [ ! -e "$name.eps" ] ; then
                 echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
                 exit 1
              fi
           else
-             echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
-             exit 1
+             if [ $opt_k -eq 1 ] ; then
+                echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+             fi
+             $XELATEX $name > /dev/null
+             if [ -e "$name.pdf" ] ; then
+                $PDF2EPS $name.pdf $name.eps
+                if [ ! -e "$name.eps" ] ; then
+                   echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+                   exit 1
+                fi
+             else
+                echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
+                exit 1
+             fi
           fi
        fi
     fi
