Version 2.3.2

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -22,7 +22,10 @@
 
 DVIPS="dvips -q -l 1 -E -R"
 LATEX="latex --interaction batchmode --output-format dvi"
+PDFLATEX="latex --interaction batchmode --output-format pdf"
+XELATEX="xelatex --interaction batchmode"
 CONVERT="convert"
+PDF2EPS="eps2eps"
 GREP="grep"
 AWK="awk"
 SED="sed"
@@ -31,7 +34,7 @@ SED="sed"
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
 TEXINPSEP=":" #Unix
 #TEXINPSEP=";"  #MS Windows
-VERSION="1.8"
+VERSION="1.20"
 
 help()
 {
@@ -44,7 +47,7 @@ OPTIONS:
          -c color image
          -g gray image  
          -m monochrome  (default)
-         -e create EPS file
+         -e only create EPS files
          
          -d density     (default 144 dpi)
          -o offset      = density/72+2
@@ -128,20 +131,44 @@ if [ $ext = "tex" ] ; then
 
     inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
 
+    rm -f $name.dvi
+    rm -f $name.pdf
+    rm -f $name.eps
+    rm -f $name.png
+
     $LATEX $name > /dev/null
     
-    if [ ! -e "$name.dvi" ] ; then
-        echo "latex2png: error: latex failed to translate $name.tex to $name.dvi"
-        exit 1
+    if [ -e "$name.dvi" ] ; then
+       $DVIPS -o $name.eps $name.dvi
+       if [ ! -e "$name.eps" ] ; then
+         echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
+         exit 1
+       fi
+    else
+       echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
+       $PDFLATEX $name > /dev/null
+       if [ -e "$name.pdf" ] ; then
+          $PDF2EPS $name.pdf $name.eps
+          if [ ! -e "$name.eps" ] ; then
+             echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+             exit 1
+          fi
+       else
+          echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+          $XELATEX $name > /dev/null
+          if [ -e "$name.pdf" ] ; then
+             $PDF2EPS $name.pdf $name.eps
+             if [ ! -e "$name.eps" ] ; then
+                echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+                exit 1
+             fi
+          else
+             echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
+             exit 1
+          fi
+       fi
     fi
-    
-    $DVIPS -o $name.eps $name.dvi
-    
-    if [ ! -e "$name.eps" ] ; then
-        echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
-        exit 1
-    fi
-
+ 
     if [ $opt_eps ] ; then
         if [ $inline -eq 1 ] ; then
            # extract the BoundingBox of the eps with adjustment stuff
@@ -152,9 +179,30 @@ if [ $ext = "tex" ] ; then
            # now create an eps without the adjustment stuff
            $SED -e "s/\^I_g//" $name.tex >$name.tmp
            rm $name.tex
+           rm $name.pdf
+           rm $name.eps
            mv $name.tmp $name.tex
            $LATEX $name > /dev/null
-           $DVIPS -o $name.eps $name.dvi
+           if [ -e "$name.dvi" ] ; then
+              $DVIPS -o $name.eps $name.dvi
+           else
+              echo "latex2png: latex failed to translate $name.tex w/o adj to $name.dvi, trying pdflatex"
+              $PDFLATEX $name > /dev/null
+              if [ ! -e "$name.pdf" ] ; then
+                 echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
+                 $XELATEX $name > /dev/null
+                 if [ ! -e "$name.pdf" ] ; then
+                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf"
+                    exit 1
+                 fi
+              fi
+              $PDF2EPS $name.pdf $name.eps
+           fi
+           if [ ! -e "$name.eps" ] ; then
+              echo "latex2png: error: failed to translate $name.tex to $name.eps"
+              exit 1
+           fi
+
            # extract the BoundingBox of the eps without adjustment stuff
            bbb=`${GREP} -C 0 %%BoundingBox: $name.eps`
            llyfin=$(echo $bbb | $AWK -F" " '{print $3}' )
@@ -172,15 +220,15 @@ if [ $ext = "tex" ] ; then
            fi
         fi
         if [ $opt_k -eq 0 ] ; then
-            rm -f $name.dvi $name.aux $name.log
+            rm -f $name.dvi $name.aux $name.log $name.out
         fi
         exit 0
     fi
     
 fi
 
-# WH: added "-type PaletteMatte" to ensure compatibility with older versions of Word and with IrfanView
-$CONVERT $out -units PixelsPerInch -density ${opt_d}x${opt_d} -trim +repage $name.eps -type PaletteMatte $name.png
+# WH: added "-type TrueColor" to ensure compatibility with older versions of Word and with IrfanView
+$CONVERT -units PixelsPerInch -density ${opt_d}x${opt_d} -trim +repage $name.eps -type TrueColor $out $name.png
 
 if [ ! -e "$name.png" ] ; then
     echo "latex2png: error: convert (ImageMagick) failed to translate $name.eps to $name.png"
@@ -206,7 +254,7 @@ if [ $inline -eq 1 ] ; then
 	# strip the initial dot and white space on the left
 	# we must keep the white space on the bottom so we add border on the east
 	# so that the bottom does not get trimmed away
-	$CONVERT $name-tmp.png -chop ${width}x0 -gravity East -background white -splice 1x0 -trim +repage -type PaletteMatte $name.png
+	$CONVERT $name-tmp.png -chop ${width}x0 -gravity East -background white -splice 1x0 -trim +repage $name.png
 
 	# extract first column of png and stick it in a bitmap
 	$CONVERT $name-tmp.png -crop 1x0 +repage $name.pbm
@@ -217,9 +265,9 @@ if [ $inline -eq 1 ] ; then
 fi
 
 if [ $opt_k -eq 0 ] ; then
-    rm -f $name.dvi $name.aux $name.log $name-tmp.png
+    rm -f $name-tmp.png
     if [ $ext = "tex" ] ; then
-        rm -f $name.eps
+        rm -f $name.dvi $name.aux $name.log $name.out $name.pdf $name.eps
     fi
 fi
 
